support mkfs for userspace convertor
containerd/accelerated-container-image pull request #222
Opened 2023-09-07 10:29 UTC by liulanzheng

**What this PR does / why we need it**:

add an flag --mkfs for convertor, which make ext filesystem in the bottom layer, base layer is not required under this config.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [x]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2023-09-07 12:12 UTC, liulanzheng commented
@WaberZhuang  cc

2023-09-12 04:14 UTC, yuchen0cc requested changes

2023-09-12 04:14 UTC, yuchen0cc commented on cmd/convertor/builder/overlaybd_builder.go
> +	opts := []string{"-z", "--uuid", curUUID}
missing "-t"

2023-09-12 08:32 UTC, liulanzheng commented on cmd/convertor/builder/overlaybd_builder.go
> +	opts := []string{"-z", "--uuid", curUUID}
fixed

2023-09-13 03:31 UTC, WaberZhuang approved these changes
LGTM

2023-09-13 04:17 UTC, merged